# Generated by Django 3.1.3 on 2021-05-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverSmall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='driver_money',
            field=models.IntegerField(default=0),
        ),
    ]
