# Generated by Django 3.1.3 on 2021-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('advertise_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advertise_image', models.CharField(max_length=255, null=True)),
                ('advertise_url', models.CharField(max_length=255, null=True)),
                ('advertise_starttime', models.DateTimeField(null=True)),
                ('advertise_desttime', models.DateTimeField(null=True)),
                ('advertise_state', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarRentalInfo',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_image', models.CharField(max_length=255, null=True)),
                ('car_brand', models.CharField(max_length=10, null=True)),
                ('car_color', models.CharField(max_length=10, null=True)),
                ('car_type', models.CharField(max_length=10, null=True)),
                ('car_rent', models.IntegerField(null=True)),
                ('car_inventory', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50, null=True)),
                ('city_spell', models.CharField(max_length=255, null=True)),
                ('city_firstletter', models.CharField(max_length=10, null=True)),
                ('city_smallprice', models.IntegerField(null=True)),
                ('city_bigprice', models.IntegerField(null=True)),
                ('city_note', models.CharField(max_length=255, null=True)),
                ('province_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(null=True)),
                ('employee_gh_openid', models.CharField(max_length=50, null=True)),
                ('employee_mini_openid', models.CharField(max_length=50, null=True)),
                ('employee_pwd', models.CharField(max_length=50, null=True)),
                ('employee_nickname', models.CharField(max_length=50, null=True)),
                ('employee_name', models.CharField(max_length=10, null=True)),
                ('employee_state', models.IntegerField(null=True)),
                ('employee_tel', models.IntegerField(null=True)),
                ('employee_registtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50, null=True)),
                ('role_id', models.IntegerField(null=True)),
                ('menu_url', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('news_id', models.IntegerField(null=True)),
                ('news_lang', models.CharField(max_length=50, null=True)),
                ('news_title', models.CharField(max_length=1000, null=True)),
                ('news_content', models.CharField(max_length=1000, null=True)),
                ('news_time', models.DateTimeField(null=True)),
                ('news_img', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, null=True)),
                ('role_describe', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_site', models.CharField(max_length=255, null=True)),
                ('service_img', models.CharField(max_length=255, null=True)),
                ('service_site_info', models.CharField(max_length=255, null=True)),
                ('province_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('state_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_type', models.CharField(max_length=50, null=True)),
                ('state_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
