# Generated by Django 3.1.3 on 2021-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='employee_tel',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
